### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by EdoardoSchnell** [sago007/PlatformFolders#21]
Hi, I just tried `npm i platform-folders ` but the build fails. This is the error I get:

```
C:\Users\federico.ceriani\Documents\Projects\tester-setup\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\federico.ceriani\AppData\Local\Programs\Python\Python38-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\federico.ceriani\Documents\Projects\tester-setup\node_modules\platform-folders
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

I suspect this has something to do with python? Not sure.

**Comment by sago007** [comment]
You would probably want to ask in https://github.com/kingjan1999/platform-folders as I only maintain a C++ library.

However, I can read from the error messages that you are using an old version of Node.Js (or node-gyp) that only works with python 2.7 and you are running python 3.8.

**Comment by EdoardoSchnell** [comment]
Oh man, I'm sorry, didn't realise it was two separated repos. Closing, and thanks for the hint.
